### ISSUE TITLE
Manual sync

### ISSUE THREAD

**Issue by antonkomarev** [ufocoder/yii2-SyncSocial#1]
Is there is a way to Synchronize model manually by calling method "actionSync" for example? And turn off automatic synchronization?

**Comment by ufocoder** [comment]
All manipulations with social synchronization are manually. If You configuration component correctly:

1) Firstly you must connect to social network in browser via link clicking. Example of link in view file:

``` php

use Html;

echo Html::a(
    'connect to facebook'
    Yii::$app->synchonizer->getAuthorizationUri( $service ),
    [
        'class' => 'btn btn-success btn-sm'
    ]
);
```

2) Secondary, you can run synchronization manually, like this:

``` php
$result = Yii::$app->synchronizer->syncService('facebook');
```

Also you can learn source of demo application. There's the [demo](https://github.com/ufocoder/yii2-SyncSocial-demo) of extension usage
Sorry for delayed response.

**Comment by antonkomarev** [comment]
So, any user on website can connect his\her account from social networks and sync content? Or it's available only for 1 configured account in each social network (for application owner)?
Demo application returning 502 error.

**Comment by ufocoder** [comment]
Demo application now is available. 

Yes, any user can connect to his\her account and sync only his/her account content. But, if you want to create specific access you should use Yii2 RBAC
